### ISSUE TITLE
Collision not working correctly

### ISSUE THREAD

**Issue by dungtang93** [dungtang93/pingpong#9]
Collision not working correctly for lower right corner of rectangle

The ball (circle) will overlap with the rectangle on contact, stick & slide there for few ms then bounce off, which is not the way other corners work.

https://github.com/dungtang93/pingpong/blob/b428f07d4e58571329f081434ea411a112c23286/src/physics/bump.js#L93

**Comment by dungtang93** [comment]
bug still happens on the lower right part, bump.js register that as _'bottomRight'_ instead of something like _'rightMiddle'_

**Comment by dungtang93** [comment]
the problem does not occur when the ball is hitting the _middle_ part, so we can eliminate this condition
https://github.com/dungtang93/pingpong/blob/b428f07d4e58571329f081434ea411a112c23286/src/physics/bump.js#L135

it is from one/all of these:
```
    switch (region) {
      case 'topLeft':
        point.x = r1x - r1.xAnchorOffset;
        point.y = r1y - r1.yAnchorOffset;
        break;

      case 'topRight':
        point.x = r1x + r1.width - r1.xAnchorOffset;
        point.y = r1y - r1.yAnchorOffset;
        break;

      case 'bottomLeft':
        point.x = r1x - r1.xAnchorOffset;
        point.y = r1y + r1.height - r1.yAnchorOffset;
        break;

      case 'bottomRight':
        point.x = r1x + r1.width - r1.xAnchorOffset;
        point.y = r1y + r1.height - r1.yAnchorOffset;
    }
```

**Comment by dungtang93** [comment]
#11 : no more overlap

@lemt93 
- [ ] **tweak the `bump.js` so the corner collision does not behave unrealistically**

see https://github.com/dungtang93/pingpong/pull/11#commitcomment-38880693

**Comment by lemt93** [comment]
Resolved
